#!/bin/sh

# XXX Add miglayout.jar to the CP
#for name in /usr/share/java/myprogram/*.jar ; do
#  CP=$CP:$name
#done
#CP=$CP:/usr/share/java/dep1/dep1.jar

opts="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true  # Fixes font problems with Java Apps in Linux

exec /usr/bin/java -jar -cp $CP '/usr/share/java/myprogram/JSpeak.jar' "$@"
